package main

import (
	_ "adata_crystal_spring/cmd/docs" // docs is generated by Swag CLI, you have to import it.
	"adata_crystal_spring/internal/handler"
	"adata_crystal_spring/internal/usecase"
	"adata_crystal_spring/pkg/http"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Token API
// @version 1.0
// @description Это пример API для управления токенами
// @host localhost:8080
// @BasePath /

func main() {
	router := gin.Default()

	httpClient := http.NewHttpClient()
	tokenUsecase := usecase.NewTokenUsecase(httpClient)
	tokenHandler := handler.NewTokenHandler(tokenUsecase)

	router.GET("/basic/:iinBin", tokenHandler.GetBasicData)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	router.Run(":8080")
}
